from typing import Union

INITIAL_WIDTH : int   = 100
INITIAL_SPACING : int = 15
INITIAL_INNER_SPACING = 10
INITIAL_ORIGIN_X : int = 50
INITIAL_ORIGIN_Y : int = 30
INITIAL_PADDING : int = 10
DEFAULT_COLOR : Union[str,int] = "blue"
INITIAL_PADDING : int = 10