[game_config]
title = "Bar chart title"
x_axis_label = "x axis"
y_axis_label = "y axis"
instructions = "Fill in the 1,2,3,4,1 sequence."
plot_width = 1000
plot_height = 500

[game_config.origin]
x = 50
y = 30

[bar_chart]
names = [["a","b","c","d"],["z"]]
groups = [[1,2,3,4],[1]]
is_guess = [[false,false,true,true],[true]]
ccolors = [["#F5AD27","#F5AD27","#F5AD27","#00AD27"],["#F5ADF7"]]